#!/bin/bash


fix_lsb_release() {
    local file=/etc/lsb-release

    if [[ -z "`grep "^DISTRIB_RELEASE=" $file`" ]] ; then
        # add missing DISTRIB_RELEASE=
        echo "DISTRIB_RELEASE=rolling" >> "$file"
    fi
    sed -i "$file" \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=ExelentOS|' \
        -e 's|^DISTRIB_RELEASE=.*$|DISTRIB_RELEASE=2.04|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"ExelentOS\"|'
}

fix_repo_key() {
	sudo pacman-key --recv-keys AF9C6FE4FEFB98349614C054FEB6CA0157FE8A75
}

fix_os_release() {
    local file=/usr/lib/os-release

    sed -i "$file" \
        -e 's|^NAME=.*$|NAME=\"ExelentOS\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"ExelentOS\"|' \
        -e 's|^ID=.*$|ID=exelent|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^BUILD_ID=.*$|BUILD_ID=2.04|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://exelentos.github.io\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://exelentos.github.io/wiki\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://github.com/exelentos/exelentos-iso"|' \
        -e 's|^LOGO=.*$|LOGO=exelentos|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

	# fix issue file
    echo "ExelentOS codename:andromeda|reborn" > /etc/issue 
    cat /etc/issue > /usr/share/factory/etc/issue
}

main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  fix_os_release ;;
        lsb-release) fix_lsb_release ;;
	repokey) fix_repo_key ;;
        "")          fix_os_release
                     fix_lsb_release
		     fix_repo_key
                     ;;
    esac
}

main "$@"
