#!/bin/bash


fix_lsb_release() {
    local file=/etc/lsb-release

    if [[ -z "`grep "^DISTRIB_RELEASE=" $file`" ]] ; then
        # add missing DISTRIB_RELEASE=
        echo "DISTRIB_RELEASE=rolling" >> "$file"
    fi
    sed -i "$file" \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=ExelentOS|' \
        -e 's|^DISTRIB_RELEASE=.*$|DISTRIB_RELEASE=2.04|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"ExelentOS\"|'
}

fix_repo_key() {
	sudo pacman-key --add /usr/share/exelent.gpg
	sudo pacman-key --lsign-key AF9C6FE4FEFB98349614C054FEB6CA0157FE8A75
}

fix_os_release() {
    local file=/usr/lib/os-release

    sed -i "$file" \
        -e 's|^NAME=.*$|NAME=\"ExelentOS\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"ExelentOS\"|' \
        -e 's|^ID=.*$|ID=exelent|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^BUILD_ID=.*$|BUILD_ID=2.04|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://exelentos.github.io\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://exelentos.github.io/wiki\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://github.com/exelentos/exelentos-iso"|' \
        -e 's|^LOGO=.*$|LOGO=exelentos|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

	# fix issue file
    echo "ExelentOS codename:andromeda|reborn" > /etc/issue 
    cat /etc/issue > /usr/share/factory/etc/issue
}

fix_default_grub() {
   if [[ $(cat /etc/default/grub | grep andromeda) ]]
   then
	echo "already installed"
   else
	echo 'GRUB_THEME="/usr/share/grub/themes/andromeda/theme.txt"' >> /etc/default/grub
   fi
}

fix_calamares() {
   if [[ $(ls /usr/bin/calamares_polkit) ]] 
   then
	   echo already exists
   else
	   echo "#!/bin/bash" >> /usr/bin/calamares_polkit
	   echo 'if [ $(which pkexec) ]; then' >> /usr/bin/calamares_polkit
	   echo '	sudo "/usr/bin/calamares" "$@" "-d"' >> /usr/bin/calamares_polkit
	   echo 'else' >> /usr/bin/calamares_polkit
	   echo '	/usr/bin/calamares "$@" "-d"' >> /usr/bin/calamares_polkit
	   echo 'fi' >> /usr/bin/calamares_polkit
	   chmod +x /usr/bin/calamares_polkit
	   sed -i 's|Exec=sh -c "pkexec calamares"|Exec=sh -c "calamares_polkit"|' /usr/share/applications/calamares.desktop

   fi
}


main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  fix_os_release ;;
        lsb-release) fix_lsb_release ;;
	repokey) fix_repo_key ;;
	grub) fix_default_grub ;;
	calamares) fix_calamares ;;
        "")          fix_os_release
                     fix_lsb_release
		     fix_repo_key
		     fix_default_grub
		     fix_calamares
                     ;;
    esac
}

main "$@"
