name: Trigger Repo deploy Workflow

on:
  push:
    branches:
      - main  # Or the branch you want to trigger from

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/exelentos/exelentos-iso/dispatches \
          -d '{"event_type": "trigger-event"}'
